// src/components/utils/ProjectCard.vue
<template>
  <div class="main">
    <router-link :to="project.name" class="preview">
      <img v-if="project.previewType === 'img'" :src="getImageUrl(project.name)" :alt="project.name">
      <LEDMatrixDisplay v-else-if="project.previewType === 'LEDMatrixDisplay'" :interactive="false"/>
    </router-link>
    <h2 class="title easy-on-the-eyes">{{project.title}}</h2>
    <p class="description easy-on-the-eyes">{{project.description}}</p>
  </div>
</template>

<style scoped src="@/assets/css/components/project-card.css"></style>

<script>
  import LEDMatrixDisplay from '@/components/projects/LEDMatrixDisplay.vue';

  export default {
    props: {
      project: {
        type: Object,
        required: true
      }
    },
    methods: {
      getImageUrl(name) {
        return new URL(`../../assets/images/${name}.png`, import.meta.url).href;
      }
    },
    components: {
      LEDMatrixDisplay,
    }
  }
</script>

// src/components/OLD/project-card/project-card.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
    selector: 'app-project-card',
    templateUrl: './project-card.component.html',
    styleUrls: ['./project-card.component.css']
})
export class ProjectCardComponent implements OnInit {

    constructor() { }

    @Input() projectInfo;

    ngOnInit(): void {
        console.log(this.projectInfo);
    }

}

<div class="grid">
    <a class="preview" routerLink="/{{projectInfo.name}}" [ngSwitch]='projectInfo.previewType'>
        <img *ngSwitchCase="'imgTemplate'" src="assets/images/{{projectInfo.name}}.png" alt="{{projectInfo.name}}">
        <led-matrix-display-only *ngSwitchCase="'ledMatrixTemplate'"></led-matrix-display-only>

        <img *ngSwitchDefault src="assets/images/{{projectInfo.name}}.png" alt="{{projectInfo.name}}">
    </a>
    <a class="title">
        <h1 class="easy-on-the-eyes">{{projectInfo.title}}</h1>
    </a>
    <p class="description easy-on-the-eyes">{{projectInfo.description}}</p>
</div>
